batch_size: 4
epochs: 2
img_height: 256
img_width: 832
learning_rate: 0.0001
mask_threshold: 255
model_filename: model.keras
normalization_factor: 255.0
random_state: 42
s3_bucket: self-driving-perceptron
s3_model_prefix: model-artifacts/lane_segmentation_model
tar_filename: model.tar.gz
test_size: 0.2
timestamp_format: '%Y%m%d_%H%M%S'
verbose: 2
